
train_file: ['checkpoints/data/coco_object/coco_caption_test_ocr.json']
val_file: ['checkpoints/data/coco_object/coco_caption_test_ocr.json']
test_file: ['checkpoints/data/coco_object/coco_caption_test_ocr.json']

read_local_data: True

coco_root: 'C:/Users/Loki/workspace/Hobby_CVinternship/dataset_object_detection/coco2014'  # 'img_root/coco_2014/'
bert_config: 'configs/config_bert_stride3.json'
# Add
bert_base_uncased_dir: "C:/Users/Loki/workspace/Hobby_CVinternship/dataset_object_detection/bert-base-uncased/"

image_res: 384
batch_size_train: 5
vision_width: 768
distill: True
clip_name: "ViT-B-16"
batch_size_test: 5
k_test: 128

alpha: 0.4
warm_up: True

eos: '[SEP]'
bos: '[CLS]'
prompt: ''

optimizer: {opt: adamW, lr1: 1e-5, lr2: 5e-6, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-5, epochs: 5, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}
use_checkpoint: True
